# Generated by Django 3.2 on 2022-02-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dropcap',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
