# Generated by Django 3.2 on 2022-02-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_dropcap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dropcap',
        ),
    ]
