# Generated by Django 3.2 on 2022-02-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about_author',
            field=models.TextField(default='Wade est rédacteur en chef du blogzine et fait également des reportages sur les dernières nouvelles basées à Londres.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='about_author',
            field=models.CharField(default='Un éditeur chez Blogzine', max_length=255),
        ),
    ]
