# Generated by Django 3.2 on 2022-02-02 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related', to='blog.post'),
        ),
    ]
