# Generated by Django 3.2 on 2022-02-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
